export interface Badge {
  id: string;
  name: string;
  description: string;
  icon: string;
  criteria: string;
  progress: number;
  target: number;
  earned: boolean;
}

export const BADGES: Badge[] = [
  {
    id: "first-blood",
    name: "First Blood",
    description: "Résoudre son premier challenge",
    icon: "",
    criteria: "1 challenge résolu",
    progress: 1,
    target: 1,
    earned: true,
  },
  {
    id: "linux-warrior",
    name: "Linux Warrior",
    description: "Réussir des labs Linux",
    icon: "",
    criteria: "10 labs Linux réussis",
    progress: 4,
    target: 10,
    earned: false,
  },
  {
    id: "sqli-hunter",
    name: "SQLi Hunter",
    description: "Exploiter des injections SQL",
    icon: "",
    criteria: "5 injections SQL exploitées",
    progress: 1,
    target: 5,
    earned: false,
  },
  {
    id: "web-hunter",
    name: "Web Hunter",
    description: "Résoudre des challenges Web",
    icon: "",
    criteria: "20 challenges Web réussis",
    progress: 7,
    target: 20,
    earned: false,
  },
  {
    id: "rooted",
    name: "Rooted",
    description: "Obtenir son premier shell root",
    icon: "",
    criteria: "1 escalade de privilèges réussie",
    progress: 1,
    target: 1,
    earned: true,
  },
  {
    id: "packet-sniffer",
    name: "Packet Sniffer",
    description: "Analyser une capture réseau complète",
    icon: "",
    criteria: "1 capture réseau analysée",
    progress: 0,
    target: 1,
    earned: false,
  },
  {
    id: "automator",
    name: "Automator",
    description: "Soumettre un script de reconnaissance fonctionnel",
    icon: "",
    criteria: "1 projet Python/Bash évalué",
    progress: 1,
    target: 1,
    earned: true,
  },
  {
    id: "ctf-recruit",
    name: "CTF Recruit",
    description: "Participer à sa première CTF Arena",
    icon: "",
    criteria: "1 CTF terminée",
    progress: 0,
    target: 1,
    earned: false,
  },
  {
    id: "ctf-champion",
    name: "CTF Champion",
    description: "Terminer dans le top 10 d'une CTF",
    icon: "",
    criteria: "Top 10 en CTF Arena",
    progress: 0,
    target: 10,
    earned: false,
  },
  {
    id: "method-master",
    name: "Pentester Junior",
    description: "Rapport de pentest noté ≥ 80%",
    icon: "",
    criteria: "Rapport de pentest soumis",
    progress: 0,
    target: 1,
    earned: false,
  },
  {
    id: "ad-king",
    name: "AD King",
    description: "Compromission complète d'un lab Active Directory",
    icon: "",
    criteria: "Domain admin obtenu",
    progress: 0,
    target: 1,
    earned: false,
  },
  {
    id: "junior-pentester",
    name: "Junior Pentester",
    description: "Terminer le parcours complet",
    icon: "",
    criteria: "12 niveaux validés",
    progress: 12,
    target: 12,
    earned: true,
  },
];
